"""Initial schema: users, specialties, doctors, availability

Revision ID: 582d7bf54b0e
Revises: 
Create Date: 2026-09-09 23:15:12.934895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582d7bf54b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('qualification', sa.String(length=240), nullable=True),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', 'start_time', name='uq_doctor_window')
    )
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_availability_doctor_id'), ['doctor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_availability_doctor_id'))

    op.drop_table('doctor_availability')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_approval_status'))

    op.drop_table('doctors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_slug'))

    op.drop_table('specialties')
    # ### end Alembic commands ###
