"""add blood_donors and donor_requests

Revision ID: 7bcf62b54f6a
Revises: b295ca328b89
Create Date: 2026-10-06 00:50:13.744984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcf62b54f6a'
down_revision = 'b295ca328b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('hospital_near', sa.String(length=200), nullable=True),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('donations_count', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_donors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_donors_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_donors_blood_group'), ['blood_group'], unique=False)

    op.create_table('donor_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('requester_phone', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['blood_donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_requests_donor_id'), ['donor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_requests_donor_id'))

    op.drop_table('donor_requests')
    with op.batch_alter_table('blood_donors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_donors_blood_group'))
        batch_op.drop_index(batch_op.f('ix_blood_donors_area'))

    op.drop_table('blood_donors')
    # ### end Alembic commands ###
