"""Add rejection note to doctors

Revision ID: b295ca328b89
Revises: 582d7bf54b0e
Create Date: 2026-09-20 20:06:45.419448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b295ca328b89'
down_revision = '582d7bf54b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_note', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('rejection_note')

    # ### end Alembic commands ###
